### ISSUE TITLE
Crash When Accessing Growth Accounting Specialized Display

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#234]
Crash When Accessing Growth Accounting Specialized Display

Date: 2023/20/12
Version: 7.92 .Net Development - Rebased to 1995; Also present in the equivalent install
Branch: Threat
Found by: Caleb Petry
Error Type: Display Issue
Description: When attempting to access Growth Accounting under Specialized Displays, the model crashes when I attempt to open scenarios that I have run. It opens correctly when I select the base case.

![image](https://user-images.githubusercontent.com/7695597/213781020-2a9c6b1c-e895-4f3e-b940-010e6a9ce318.png)

Exception of type 'System.Web.HttpUnhandledException' was thrown.
System.NullReferenceException: Object reference not set to an instance of an object.
at System.Web.UI.WebControls.Table.RowControlCollection.AddAt(Int32 index, Control child)
at System.Web.UI.WebControls.TableRowCollection.Add(TableRow row)
at IFsWeb.frm_GrowthAccounting.LoadGrid() in C:\Users\Public\IFs\IFsWeb\frm_GrowthAccounting.aspx.vb:line 740
at IFsWeb.frm_GrowthAccounting.cmdTable_Click(Object sender, EventArgs e) in C:\Users\Public\IFs\IFsWeb\frm_GrowthAccounting.aspx.vb:line 653
at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by caleb-petry** [comment]
Behaves normally with 7.93 GUI, closing for now.
