### ISSUE TITLE
J-Curve

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#257]
USA, Mental Health, Graph.... Blow up:

<html>
<body>
<hr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
The following error occurred:Exception of type 'System.Web.HttpUnhandledException' was thrown.System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. Parameter name: name Actual value was MentalHealthFeMales.at Microsoft.Data.Sqlite.SqliteDataRecord.GetOrdinal(String name)at Microsoft.Data.Sqlite.SqliteDataRecord.get_Item(String name)at Microsoft.Data.Sqlite.SqliteDataReader.get_Item(String name)at IFsWeb.frm_MortDisplay.LoadMortality(Int32 TotalGraphs, String sFileName, String sReg, Int32 iReg, Boolean bGrp, String sType, String sGender, Int32 iYr, Boolean bReport) in D:\Users\Public\IFs\IFsWeb\frm_MortDisplay.aspx.vb:line 1469at IFsWeb.frm_MortDisplay.LoadSetJ() in D:\Users\Public\IFs\IFsWeb\frm_MortDisplay.aspx.vb:line 723at IFsWeb.frm_MortDisplay.LoadSet() in D:\Users\Public\IFs\IFsWeb\frm_MortDisplay.aspx.vb:line 613at IFsWeb.frm_MortDisplay.cmdGraph_Click(Object sender, EventArgs e) in D:\Users\Public\IFs\IFsWeb\frm_MortDisplay.aspx.vb:line 573at System.Web.UI.WebControls.Button.OnClick(EventArgs e)at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)The IFs project will appreciate and thank users that report any errors they might find, in either the web-based or stand-alone version of IFs including a reproducible path for generating the error (please provide details clearly) to jsolorza@du.edu. Thank you for using IFs and making it better.
--

</body>
</html>The following error occurred:

Exception of type 'System.Web.HttpUnhandledException' was thrown.
System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. Parameter name: name Actual value was MentalHealthFeMales.
at Microsoft.Data.Sqlite.SqliteDataRecord.GetOrdinal(String name)
at Microsoft.Data.Sqlite.SqliteDataRecord.get_Item(String name)
at Microsoft.Data.Sqlite.SqliteDataReader.get_Item(String name)
at IFsWeb.frm_MortDisplay.LoadMortality(Int32 TotalGraphs, String sFileName, String sReg, Int32 iReg, Boolean bGrp, String sType, String sGender, Int32 iYr, Boolean bReport) in D:\Users\Public\IFs\IFsWeb\frm_MortDisplay.aspx.vb:line 1469
at IFsWeb.frm_MortDisplay.LoadSetJ() in D:\Users\Public\IFs\IFsWeb\frm_MortDisplay.aspx.vb:line 723
at IFsWeb.frm_MortDisplay.LoadSet() in D:\Users\Public\IFs\IFsWeb\frm_MortDisplay.aspx.vb:line 613
at IFsWeb.frm_MortDisplay.cmdGraph_Click(Object sender, EventArgs e) in D:\Users\Public\IFs\IFsWeb\frm_MortDisplay.aspx.vb:line 573
at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

The IFs project will appreciate and thank users that report any errors they might find, in either the web-based or stand-alone version of IFs including a reproducible path for generating the error (please provide details clearly) to [jsolorza@du.edu](mailto:jsolorza@du.edu?body=Exception%20of%20type). Thank you for using IFs and making it better.

**Comment by PardeeCenterIFs** [comment]
I guess we had not tested this since we migrated to SQLite, there was a problem with the casing of filters for Mental Health, Resp. Infections and the Total for the 3 big categories. Only when using Females or Total. This issue has been solved, and the fix will be included in version 8.18.
