### ISSUE TITLE
.NET 7.66 Growth Accounting Graph

### ISSUE THREAD

**Issue by markmeziere** [PardeeCenterDU/IFs-Issues-Tracking#52]
Display -> Specialized Displays for Issues -> Growth Accounting

Graph option does not work for any combination of Region, Economic Sector, Scenario, or Variables.

When "Graph" is clicked the message below error message below is displayed:

The following error occurred:

Exception of type 'System.Web.HttpUnhandledException' was thrown.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at System.Collections.Generic.List`1.get_Item(Int32 index)
at IFsWeb.frm_GrowthAccounting.PackJScritpBuilder() in c:\shortPath\Source\frm_GrowthAccounting.aspx.vb:line 1664
at IFsWeb.frm_GrowthAccounting.DrawGraph() in c:\shortPath\Source\frm_GrowthAccounting.aspx.vb:line 1591
at IFsWeb.frm_GrowthAccounting.cmdDraw_Click(Object sender, EventArgs e) in c:\shortPath\Source\frm_GrowthAccounting.aspx.vb:line 1444
at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by PardeeCenterIFs** [comment]
JRS: Got it, I needed to add some explicit conversion statements in there. This fix will be included in version 7.67.
